version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:4.0.28
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379
    command: redis-server --loglevel warning
    volumes:
      - ~/.docker/redis:/data
    # networks:
    #   - common

  postgres:
    image: postgres:14.6-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DATABASE=databaseName
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ~/.docker/db:/var/lib/postgresql/data
    # networks:
    #   - common

volumes:
  mysql-data:
  mongodb-data:
  # common: 
  #   driver: bridge